### ISSUE TITLE
[discussion] rationale for Akka and Scala

### ISSUE THREAD

**Issue by viktortnk** [input-output-hk/psg-cardano-wallet-api#45]
Hi there

_The purpose of this issue is general discussion, not arguing for a change_

I quickly glimpsed over codebase and was wondering on the technology pick for this project, specifically Scala and Akka.
I'm big fan of Scala and built my whole company backend on top of it's ecosystem. Learning over many years I'd be vary of the choice of Akka + Scala for a driver, which is aimed to used by a community

I see the stated purpose is very simple

> This artefact wraps calls to that API to make them easily accessible to Java or Scala developers.

If we speak about wider adoption by projects, the downsides are coming from the dependency management
- for Scala projects people would need to align versions of Scala and project will need to support cross-version building
- for java projects it is an overkill to bring Scala dependency
- many Scala projects already have akka-http in their stack, so they will need fight version compatibility between their version and this client's

Overall, for simple wrapper which is sending HTTP requests and parsing JSON responsed I think this technology stack might be an overkill and could bring some friction for adopting this library by developers

In contrast, when Java API well designed and provides asynchronous non-blocking capabilities, I usually have no issues using it from a Scala stack
I think the library core could almost be built as zero-dependency

One of the examples is Kafka, which started heavy on Scala for their driver and then realised that it is difficult to use and moved it to plan java then

**Comment by mcsherrylabs** [comment]
Just FYI -> https://github.com/input-output-hk/psg-cardano-wallet-api#implementation

In Q1 of next year we should also see auto generated clients come online.
